name: LGUHC
version: 1.0
main: fr.caraito.lguhc.Main
api-version: 1.8

commands:
  lgstart:
    description: Main command for LGUHC plugin
    usage: /lgstart
    permission: lguhc.start
  lgworld:
    description: Gérer les mondes LG
    permission: lguhc.world
  lgspawn:
    description: Retourner au spawn principal (monde world)
  lgstop:
    description: Arrête la partie de Loup-Garou UHC en cours.
    permission: lguhc.admin
  lgconfig:
    description: Gérer la configuration du plugin LGUHC
    permission: lguhc.admin
  lgrevive:
    description: Revivre un joueur mort.
  lginfo:
    description: Affiche les informations de votre rôle et la liste des loups.
